// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ourSelf.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OurSelf struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	CpuNum               int32    `protobuf:"varint,2,opt,name=CpuNum,proto3" json:"CpuNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OurSelf) Reset()         { *m = OurSelf{} }
func (m *OurSelf) String() string { return proto.CompactTextString(m) }
func (*OurSelf) ProtoMessage()    {}
func (*OurSelf) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a20103a9f841c1, []int{0}
}

func (m *OurSelf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OurSelf.Unmarshal(m, b)
}
func (m *OurSelf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OurSelf.Marshal(b, m, deterministic)
}
func (m *OurSelf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OurSelf.Merge(m, src)
}
func (m *OurSelf) XXX_Size() int {
	return xxx_messageInfo_OurSelf.Size(m)
}
func (m *OurSelf) XXX_DiscardUnknown() {
	xxx_messageInfo_OurSelf.DiscardUnknown(m)
}

var xxx_messageInfo_OurSelf proto.InternalMessageInfo

func (m *OurSelf) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *OurSelf) GetCpuNum() int32 {
	if m != nil {
		return m.CpuNum
	}
	return 0
}

func init() {
	proto.RegisterType((*OurSelf)(nil), "OurSelf")
}

func init() { proto.RegisterFile("ourSelf.proto", fileDescriptor_d8a20103a9f841c1) }

var fileDescriptor_d8a20103a9f841c1 = []byte{
	// 86 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2f, 0x2d, 0x0a,
	0x4e, 0xcd, 0x49, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe5, 0x62, 0xf7, 0x87, 0x08,
	0x08, 0x09, 0x71, 0xb1, 0x38, 0xa6, 0xa4, 0x14, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0xd9, 0x42, 0x62, 0x5c, 0x6c, 0xce, 0x05, 0xa5, 0x7e, 0xa5, 0xb9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a,
	0xac, 0x41, 0x50, 0x5e, 0x12, 0x1b, 0x58, 0xb7, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x54, 0xcb,
	0xea, 0x8c, 0x4e, 0x00, 0x00, 0x00,
}
