// Code generated by protoc-gen-go. DO NOT EDIT.
// source: report.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Report struct {
	AspireMQ             []*AspireMQ `protobuf:"bytes,1,rep,name=AspireMQ,proto3" json:"AspireMQ,omitempty"`
	Product              []*Product  `protobuf:"bytes,2,rep,name=Product,proto3" json:"Product,omitempty"`
	Consumer             []*Consumer `protobuf:"bytes,3,rep,name=Consumer,proto3" json:"Consumer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{0}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetAspireMQ() []*AspireMQ {
	if m != nil {
		return m.AspireMQ
	}
	return nil
}

func (m *Report) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Report) GetConsumer() []*Consumer {
	if m != nil {
		return m.Consumer
	}
	return nil
}

type AspireMQ struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AspireMQ) Reset()         { *m = AspireMQ{} }
func (m *AspireMQ) String() string { return proto.CompactTextString(m) }
func (*AspireMQ) ProtoMessage()    {}
func (*AspireMQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{1}
}

func (m *AspireMQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AspireMQ.Unmarshal(m, b)
}
func (m *AspireMQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AspireMQ.Marshal(b, m, deterministic)
}
func (m *AspireMQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AspireMQ.Merge(m, src)
}
func (m *AspireMQ) XXX_Size() int {
	return xxx_messageInfo_AspireMQ.Size(m)
}
func (m *AspireMQ) XXX_DiscardUnknown() {
	xxx_messageInfo_AspireMQ.DiscardUnknown(m)
}

var xxx_messageInfo_AspireMQ proto.InternalMessageInfo

func (m *AspireMQ) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type Product struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{2}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type Consumer struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consumer) Reset()         { *m = Consumer{} }
func (m *Consumer) String() string { return proto.CompactTextString(m) }
func (*Consumer) ProtoMessage()    {}
func (*Consumer) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eedb623aa6ca98c, []int{3}
}

func (m *Consumer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consumer.Unmarshal(m, b)
}
func (m *Consumer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consumer.Marshal(b, m, deterministic)
}
func (m *Consumer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consumer.Merge(m, src)
}
func (m *Consumer) XXX_Size() int {
	return xxx_messageInfo_Consumer.Size(m)
}
func (m *Consumer) XXX_DiscardUnknown() {
	xxx_messageInfo_Consumer.DiscardUnknown(m)
}

var xxx_messageInfo_Consumer proto.InternalMessageInfo

func (m *Consumer) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func init() {
	proto.RegisterType((*Report)(nil), "Report")
	proto.RegisterType((*AspireMQ)(nil), "AspireMQ")
	proto.RegisterType((*Product)(nil), "Product")
	proto.RegisterType((*Consumer)(nil), "Consumer")
}

func init() { proto.RegisterFile("report.proto", fileDescriptor_3eedb623aa6ca98c) }

var fileDescriptor_3eedb623aa6ca98c = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x2d, 0xc8,
	0x2f, 0x2a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xaa, 0xe2, 0x62, 0x0b, 0x02, 0xf3, 0x85,
	0x54, 0xb9, 0x38, 0x1c, 0x8b, 0x0b, 0x32, 0x8b, 0x52, 0x7d, 0x03, 0x25, 0x18, 0x15, 0x98, 0x35,
	0xb8, 0x8d, 0x38, 0xf5, 0x60, 0x02, 0x41, 0x70, 0x29, 0x21, 0x25, 0x2e, 0xf6, 0x80, 0xa2, 0xfc,
	0x94, 0xd2, 0xe4, 0x12, 0x09, 0x26, 0xb0, 0x2a, 0x0e, 0x3d, 0x28, 0x3f, 0x08, 0x26, 0x01, 0x32,
	0xca, 0x39, 0x3f, 0xaf, 0xb8, 0x34, 0x37, 0xb5, 0x48, 0x82, 0x19, 0x6a, 0x14, 0x4c, 0x20, 0x08,
	0x2e, 0xa5, 0x24, 0x87, 0xb0, 0x51, 0x48, 0x88, 0x8b, 0xc5, 0x31, 0x25, 0xa5, 0x48, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x56, 0x92, 0x85, 0x5b, 0x85, 0x55, 0x5a, 0x0e, 0x61, 0x0b,
	0x36, 0xf9, 0x24, 0x36, 0xb0, 0x0f, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x08, 0x80,
	0x6c, 0xf1, 0x00, 0x00, 0x00,
}
